# Generated by Django 4.1.7 on 2023-03-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_firstmigration"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="blog",
            index=models.Index(
                fields=["post_date"], name="blog_blog_post_da_d6c288_idx"
            ),
        ),
    ]
